import type { Metadata } from "next";
import { ClerkProvider, SignedIn, SignedOut, SignIn, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <header className="w-full flex justify-between py-6 px-8 bg-[#e0dfdf] border-b border-gray-200 mb-10">
          <h1 className="font-bold text-2xl text-gray-800">Goal-App</h1>
          <UserButton showName />
        </header>
        <main>
          <SignedOut>
            <SignIn routing="hash"/>
          </SignedOut>
          <SignedIn>
            {children}
          </SignedIn>
        </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
